# Generated by Django 3.0.1 on 2020-01-02 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arbitro',
            fields=[
                ('idarbitro', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(blank=True, max_length=30, null=True)),
                ('telefono', models.CharField(max_length=12, unique=True)),
                ('mail', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'arbitro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('idcompra', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
            ],
            options={
                'db_table': 'compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Edicion',
            fields=[
                ('idedicion', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'edicion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('identrenador', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(blank=True, max_length=30, null=True)),
                ('telefono', models.CharField(max_length=12, unique=True)),
                ('mail', models.CharField(max_length=255, unique=True)),
                ('notificaciones', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'entrenador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pista',
            fields=[
                ('idpista', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('capacidad', models.BigIntegerField()),
            ],
            options={
                'db_table': 'pista',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tenista',
            fields=[
                ('idtenista', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(blank=True, max_length=30, null=True)),
                ('telefono', models.CharField(max_length=12, unique=True)),
                ('mail', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'tenista',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipodeentrada',
            fields=[
                ('idtipo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.FloatField()),
            ],
            options={
                'db_table': 'tipodeentrada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('idtrabajador', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(blank=True, max_length=30, null=True)),
                ('telefono', models.CharField(max_length=12, unique=True)),
                ('mail', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'trabajador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(blank=True, max_length=30, null=True)),
                ('mail', models.CharField(max_length=50, unique=True)),
                ('contrasena', models.CharField(max_length=30)),
                ('notificaciones', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Compraentrada',
            fields=[
                ('idtipo', models.OneToOneField(db_column='idtipo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='tenis.Tipodeentrada')),
                ('cantidad', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'compraentrada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comprafinalizada',
            fields=[
                ('idcompra', models.OneToOneField(db_column='idcompra', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='tenis.Compra')),
                ('idcomprafin', models.BigIntegerField(unique=True)),
            ],
            options={
                'db_table': 'comprafinalizada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('idpista', models.OneToOneField(db_column='idpista', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='tenis.Pista')),
                ('fecha', models.DateField()),
                ('resultado', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'partido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tenistaedicionentrenador',
            fields=[
                ('idedicion', models.OneToOneField(db_column='idedicion', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='tenis.Edicion')),
            ],
            options={
                'db_table': 'tenistaedicionentrenador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trabaja',
            fields=[
                ('idtrabajador', models.OneToOneField(db_column='idtrabajador', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='tenis.Trabajador')),
            ],
            options={
                'db_table': 'trabaja',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asignado',
            fields=[
                ('idtrabajador', models.OneToOneField(db_column='idtrabajador', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='tenis.Trabaja')),
                ('fechafin', models.DateField()),
                ('fechaini', models.DateField()),
            ],
            options={
                'db_table': 'asignado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Compite',
            fields=[
                ('idpista', models.OneToOneField(db_column='idpista', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='tenis.Partido')),
            ],
            options={
                'db_table': 'compite',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comprapagada',
            fields=[
                ('idcompra', models.OneToOneField(db_column='idcompra', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='tenis.Comprafinalizada')),
                ('numeroticket', models.BigIntegerField(unique=True)),
            ],
            options={
                'db_table': 'comprapagada',
                'managed': False,
            },
        ),
    ]
