# Generated by Django 3.0.1 on 2020-01-03 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arbitro',
            fields=[
                ('idarbitro', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(blank=True, max_length=30, null=True)),
                ('telefono', models.CharField(max_length=12, unique=True)),
                ('mail', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'arbitro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asignado',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fechafin', models.DateField()),
                ('fechaini', models.DateField()),
            ],
            options={
                'db_table': 'asignado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('codename', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Compite',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'compite',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('idcompra', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
            ],
            options={
                'db_table': 'compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Compraentrada',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'compraentrada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('action_flag', models.IntegerField()),
                ('change_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(blank=True, null=True)),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Edicion',
            fields=[
                ('idedicion', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'edicion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('identrenador', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(blank=True, max_length=30, null=True)),
                ('telefono', models.CharField(max_length=12, unique=True)),
                ('mail', models.CharField(max_length=255, unique=True)),
                ('notificaciones', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'entrenador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('resultado', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'partido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pista',
            fields=[
                ('idpista', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('capacidad', models.BigIntegerField()),
            ],
            options={
                'db_table': 'pista',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tenista',
            fields=[
                ('idtenista', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(blank=True, max_length=30, null=True)),
                ('telefono', models.CharField(max_length=12, unique=True)),
                ('mail', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'tenista',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tenistaedicionentrenador',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tenistaedicionentrenador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipodeentrada',
            fields=[
                ('idtipo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.FloatField()),
            ],
            options={
                'db_table': 'tipodeentrada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trabaja',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'trabaja',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('idtrabajador', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(blank=True, max_length=30, null=True)),
                ('telefono', models.CharField(max_length=12, unique=True)),
                ('mail', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'trabajador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(blank=True, max_length=30, null=True)),
                ('mail', models.CharField(max_length=50, unique=True)),
                ('contrasena', models.CharField(max_length=30)),
                ('notificaciones', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comprafinalizada',
            fields=[
                ('idcompra', models.OneToOneField(db_column='idcompra', on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='tenis.Compra')),
                ('idcomprafin', models.BigIntegerField(unique=True)),
            ],
            options={
                'db_table': 'comprafinalizada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comprapagada',
            fields=[
                ('idcompra', models.OneToOneField(db_column='idcompra', on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='tenis.Comprafinalizada')),
                ('numeroticket', models.BigIntegerField(unique=True)),
            ],
            options={
                'db_table': 'comprapagada',
                'managed': False,
            },
        ),
    ]
